<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="laptop" failures="1" tests="6" name="Test5" time="0.116" errors="0" timestamp="2025-03-11T09:15:20 IST">
  <testcase classname="tutorial.testng.LoginTests" name="testInvalidCredentialsLogin" time="0.003"/>
  <testcase classname="tutorial.testng.LoginTests" name="testInvalidEmail" time="0.041">
    <failure type="java.lang.AssertionError" message="I was forced to fail">
      <![CDATA[java.lang.AssertionError: I was forced to fail
at tutorial.testng.LoginTests.testInvalidEmail(LoginTests.java:119)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- testInvalidEmail -->
  <testcase classname="tutorial.testng.LoginTests" name="testUnregisteredLogin" time="0.004"/>
  <testcase classname="tutorial.testng.LoginTests" name="testValidLogin" time="0.002"/>
  <testcase classname="tutorial.testng.LoginTests" name="userRegistration" time="0.005"/>
  <testcase classname="tutorial.testng.LoginTests" name="testBlankEmailPassword" time="0.0">
    <skipped/>
  </testcase> <!-- testBlankEmailPassword -->
</testsuite> <!-- Test5 -->
